name: echopro
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  # Jupyter stack
  - ipympl
  - ipywidgets<8
  - jupyter_contrib_nbextensions
  - nb_conda_kernels
  - notebook<6.5
  # Computational stack
  - geopandas
  - geopy
  - numba
  - openpyxl
  - PyYAML
  - shapely<2
  - xarray
  - pip:
    - git+https://github.com/uw-echospace/EchoPro.git
