name: echopro_conda
channels:
  - conda-forge
dependencies:
  - python=3.9
  - geopandas
  - PyYAML=6.0
  - xarray=2022.3.0
  - geopy=2.2.0
  - openpyxl=3.0.9
  - ipywidgets=7.7.0
  - ipympl=0.8.7
  - numba=0.55.1