####################################################################################################
# FEAT hake survey: comparing EchoPro and Echopop report outputs across years
# ---------------------------------------------------------------------------
# This ingests the reports generated by Echopop and compares them with those produced by EchoPro.
# This script requires that the reports either be in separate folders, or have unique names that
# differentiate the EchoPro and Echopop reports.
# ==================================================================================================
# PARAMETER ENTRY
# ---------------
from pathlib import Path
from typing import Callable
from echopop.workflows.nwfsc_feat import comparisons as comp

# ==================================================================================================
# USER CONFIGURATION
# ------------------

# OUTPUT FIGURE FILEPATH
SAVE_FILEPATH = Path("C:/Data/EchopopData/cross_year_comparisons_2025.png")

# PARQUET CACHE DIRECTORY
# Set to None to disable caching entirely.
CACHE_DIR = Path("C:/Data/EchopopData/.cache")

# YEARS TO PROCESS
YEARS = [1995, 1998, 2001, 2003, 2005, 2007, 2009, 2011, 2012, 2013, 2015, 2017, 2019, 2021]

# DIRECTORY TEMPLATES
# -------------------
# Define functions that accept a year (int) and return a Path to the report directory.
# Adjust these to match your local folder structure. Examples:
#   lambda year: Path(f"C:/Data/EchopopData/reports/{year}/echopro/")
#   lambda year: Path(f"C:/Data/EchopopData/echopop_{year}/reports_echopro")
ECHOPRO_ROOT: Callable[[int], Path] = lambda year: Path(
    f"C:/Data/EchopopData/echopop_{year}/reports_echopro"
)
ECHOPOP_ROOT: Callable[[int], Path] = lambda year: Path(
    f"C:/Data/EchopopData/echopop_{year}/reports_updated_biodata"
)

# FILENAME PATTERNS
# -----------------
# Both Echopop and EchoPro filenames are matched via regex pattern. An exact filename string is
# also valid and will match only that file. Each pattern must match exactly one file per directory.
# Examples:
#   Exact:  "transect_population_results_full.xlsx"
#   Regex:  r"^EchoPro_kriged_output(?:-.*)?_0\.xlsx$"
ECHOPOP_PATTERNS = {
    "transect": r"transect_population_results_full\.xlsx",
    "kriging": r"kriged_biomass_mesh_full\.xlsx",
}
ECHOPRO_PATTERNS = {
    "transect": r"^EchoPro_un-kriged_output(?:-.*)?_0\.xlsx$",
    "kriging": r"^EchoPro_kriged_output(?:-.*)?_0\.xlsx$",
}

# PARALLELIZATION (optional)
# --------------------------
# Set to None to load files sequentially (default, safest across all OS).
# Set to a positive integer (e.g. 8) to enable parallel loading via a thread pool.
MAX_WORKERS = None

# ==================================================================================================
# LOAD ALL DATA
ECHOPRO_DATASETS, ECHOPOP_DATASETS = comp.load_all_geodata_reports(
    years=YEARS,
    echopro_root=ECHOPRO_ROOT,
    echopop_root=ECHOPOP_ROOT,
    echopop_patterns=ECHOPOP_PATTERNS,
    echopro_patterns=ECHOPRO_PATTERNS,
    cache_dir=CACHE_DIR,
    max_workers=MAX_WORKERS,
)

# ==================================================================================================
# COMPUTE DIFFERENCES
differences, signed_pct_diff = comp.compute_dataset_differences(
    echopro_datasets=ECHOPRO_DATASETS,
    echopop_datasets=ECHOPOP_DATASETS,
)

# ==================================================================================================
# PLOT DIFFERENCES [%]
comp.plot_dataset_differences(
    signed_pct_diff,
    save_filepath=SAVE_FILEPATH,
)