####################################################################################################
# FEAT hake survey: comparing EchoPro and Echopop report outputs across years
# ---------------------------------------------------------------------------
# This ingests the reports generated by Echopop and compares them with those produced by EchoPro. 
# This script requires that the reports either be in separate folders, or have unique names that 
# differentiate the EchoPro and Echopop reports.
# ==================================================================================================
# PARAMETER ENTRY
# ---------------
from pathlib import Path
from typing import Literal
import re
import os
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from echopop.workflows.nwfsc_feat.workflows import comparisons as comp
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# SAVE FILEPATH FOR OUTPUT FIGURE
SAVE_FILEPATH = Path("C:/Data/EchopopData/cross_year_comparisons.png")
# YEARS TO PROCESS
years = [1995, 1998, 2001, 2003, 2005, 2007, 2009, 2011, 2012, 2013, 2015, 2017, 2019, 2021]
# DATA DIRECTORIES
# ----------------
# ROOT REPORT DIRECTORY FOR ECHOPOP - GENERATION FUNCTION
def generate_echopro_root(year: int): 
    return Path(f"C:/Data/EchopopData/echopop_{year}/reports_echopro")
# ROOT REPORT DIRECTORY FOR ECHOPRO - GENERATION FUNCTION
def generate_echopop_root(year: int):
    return Path(f"C:/Data/EchopopData/echopop_{year}/reports")
# ==================================================================================================
# FUNCTION FOR INGESTION
def get_report(
    filepath: Path, 
    dataset: Literal["echopop", "echopro"], 
    type: Literal["transect", "kriging"]
):
    # Validate filepath
    if not filepath.exists():
        raise FileNotFoundError(f"Filepath could not be found: '{filepath.as_posix()}'.")
    
    # Find file based on dataset
    if dataset == "echopop":
        if type == "kriging": 
            file = filepath / "kriged_biomass_mesh_full.xlsx"
        else:
            file = filepath / "transect_population_results_nonzero.xlsx"
    else:
        if type == "kriging": 
            # ---- Expected file pattern
            pattern = re.compile(r"^EchoPro_kriged_output(?:-.*)?_1\.xlsx$")
        else:
            # ---- Expected file pattern
            pattern = re.compile(r"^EchoPro_un-kriged_output(?:-.*)?_1\.xlsx$")
        # ---- Check across available files in directory
        matched_files = [
            f for f in os.listdir(filepath)
            if pattern.match(f)
        ]
        # ---- Validate
        if matched_files and len(matched_files) == 1:
            file = filepath / matched_files[0]
        elif len(matched_files) > 1:
            raise LookupError(
                f"Multiple files matching pattern for {dataset}-{type} in '{filepath.as_posix()}'."
            )
        else:
            raise FileNotFoundError(
                f"No files matching pattern for {dataset}-{type} found in '{filepath.as_posix()}'."
            )

    # Read in the file and return
    return comp.read_geodata(file)
# ==================================================================================================
# ITERATE ACROSS YEARS AND STORE IN CONTAINERS
ECHOPRO_DATASETS = {
    "transect": {
        year: get_report(generate_echopro_root(year), dataset="echopro", type="transect") 
        for year in years
    },
    "kriging": {
        year: get_report(generate_echopro_root(year), dataset="echopro", type="kriging") 
        for year in years
    }
}

ECHOPOP_DATASETS = {
    "transect": {
        year: get_report(generate_echopop_root(year), dataset="echopop", type="transect") 
        for year in years
    },
    "kriging": {
        year: get_report(generate_echopop_root(year), dataset="echopop", type="kriging") 
        for year in years
    }
}
# ==================================================================================================
# SUM ABUNDANCE, BIOMASS, NASC ACROSS ALL
ECHOPRO_SUMS = {
    "transect": {
        year: ECHOPRO_DATASETS["transect"][year][["abundance", "biomass", "nasc"]].sum()
        for year in years
    },
    "kriging": {
        year: ECHOPRO_DATASETS["kriging"][year][["abundance", "biomass", "nasc"]].sum()
        for year in years
    }
}

ECHOPOP_SUMS = {
    "transect": {
        year: ECHOPOP_DATASETS["transect"][year][["abundance", "biomass", "nasc"]].sum()
        for year in years
    },
    "kriging": {
        year: ECHOPOP_DATASETS["kriging"][year][["abundance", "biomass", "nasc"]].sum()
        for year in years
    }
}

# CONVERT TO DATAFRAME
echopro = pd.concat(
    {
        outer_k: pd.DataFrame(inner_v).T for outer_k, inner_dict in ECHOPRO_SUMS.items() 
        for inner_v in [inner_dict]
    },
    names=["method", "year"]
).sort_index()

echopop = pd.concat(
    {
        outer_k: pd.DataFrame(inner_v).T for outer_k, inner_dict in ECHOPOP_SUMS.items() 
        for inner_v in [inner_dict]
    },
    names=["method", "year"]
).sort_index()

# COMPUTE DIFFERENCES
differences = echopro - echopop

# CONVERT TO PERCENT DIFFERENCE
signed_pct_diff = np.sign(differences) * np.abs(differences) / ((echopro + echopop) / 2) * 1e2

# PLOT THE DIFFERENCES AS A GRID FOR OVERVIEW
gridded_data = signed_pct_diff.unstack()

def fmt_percent(df):
    return df.map(lambda x: f"{x:.1f}%" if not pd.isna(x) else "")

# For each panel:
annot_transect = fmt_percent(signed_pct_diff.loc["transect"])
annot_kriging = fmt_percent(signed_pct_diff.loc["kriging"])

# Find global vmin/vmax for consistent color scaling
vmin = signed_pct_diff.min().min()
vmax = signed_pct_diff.max().max()

fig, axes = plt.subplots(1, 2, figsize=(14, 6), sharey=True)

# ---- Transect values
sns.heatmap(
    signed_pct_diff.loc["transect"], 
    ax=axes[0], 
    cmap="coolwarm", 
    vmin=vmin,
    vmax=vmax,
    center=0, 
    annot=annot_transect, 
    fmt="",
    linewidths=1,
    linecolor="black",
    cbar=True,
    cbar_kws={"label": "% Difference (EchoPro - Echopop)"}
)
axes[0].set_title("Transect")
axes[0].set_ylabel("Year")
axes[0].set_xlabel("")

# ---- Kriging values
sns.heatmap(
    signed_pct_diff.loc["kriging"], 
    ax=axes[1], 
    cmap="coolwarm", 
    vmin=vmin,
    vmax=vmax,
    center=0,
    annot=annot_kriging,
    fmt="",
    linewidths=1,
    linecolor="black",
    cbar=True,
    cbar_kws={"label": "% Difference (EchoPro - Echopop)"}
)
axes[1].set_title("Kriging")
axes[1].set_ylabel("")  # Only show y-label on first panel
axes[1].set_xlabel("")

axes[0].set_xticklabels(["Abundance", "Biomass", "NASC"])
axes[1].set_xticklabels(["Abundance", "Biomass", "NASC"])

plt.tight_layout()

plt.savefig(SAVE_FILEPATH, dpi=300)
plt.show()