####################################################################################################
# FEAT hake survey: comparing EchoPro and Echopop report outputs
# --------------------------------------------------------------
# This ingests the reports generated by Echopop and compares them with those produced by EchoPro. 
# This script requires that the reports either be in separate folders, or have unique names that 
# differentiate the EchoPro and Echopop reports.
# ==================================================================================================
# PARAMETER ENTRY
# ---------------
from pathlib import Path
import pandas as pd
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# DATA DIRECTORIES
# ----------------
# ROOT REPORT DIRECTORY FOR ECHOPOP
ECHOPOP_ROOT = Path("C:/Data/EchopopData/echopop_2023/reports")
# ROOT REPORT DIRECTORY FOR ECHOPRO
ECHOPRO_ROOT = Path("C:/Data/EchopopData/echopop_2023/reports")
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# SAVE DIRECTORIES
# ----------------
SAVE_DIRECTORY = ECHOPOP_ROOT / "echopop_echopro_comparisons"
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# CREATE DICTIONARY MAP THAT LINKS EACH ECHOPOP FILE WITH EACH COMPARABLE ECHOPRO FILE
# ---- Assign the Echopop output name to the equivalent EchoPro report filename in their respective 
# ---- report-type keys
ECHOPRO_TO_ECHOPOP_FILE_MAP = {
    "aged_length_haul_counts": {
        "aged_len_haul_counts_table.xlsx": "aged_length_haul_counts.xlsx"
    },
    "total_length_haul_counts": {
        "total_len_haul_counts_table.xlsx": "total_length_haul_counts.xlsx"
    },
    "aged_kriged_mesh_biomass_full": {
        "EchoPro_kriged_aged_output-2023_1.xlsx": "kriged_aged_biomass_mesh_full.xlsx"
    },
    "aged_kriged_mesh_biomass_subset": {
        "EchoPro_kriged_aged_output-2023_0.xlsx": "kriged_aged_biomass_mesh_nonzero.xlsx"
    },
    "kriged_mesh_biomass_full": {
        "EchoPro_kriged_output-08-Dec-2023_0.xlsx": "kriged_biomass_mesh_full.xlsx"
    },
    "kriged_mesh_biomass_subset": {
        "EchoPro_kriged_output-08-Dec-2023_1.xlsx": "kriged_biomass_mesh_nonzero.xlsx"
    },
    "kriging_input": {
        "kriging_input.xlsx": "kriging_input_report.xlsx"
    },
    "kriged_length_age_abundance": {
        "kriged_len_age_abundance_table.xlsx": "kriged_length_age_abundance_report.xlsx"
    },
    "kriged_length_age_biomass": {
        "kriged_len_age_biomass_table.xlsx": "kriged_length_age_biomass_report.xlsx"
    },
    "aged_transect_biomass_full": {
        "EchoPro_un-kriged_aged_output-2023_0.xlsx": "transect_aged_biomass_report_full.xlsx"
    },
    "aged_transect_biomass_subset": {
        "EchoPro_un-kriged_aged_output-2023_1.xlsx": "transect_aged_biomass_report_nonzero.xlsx"
    },
    "transect_length_age_abundance": {
        "un-kriged_len_age_abundance_table.xlsx": "transect_length_age_abundance_report.xlsx"
    },
    "transect_length_age_biomass": {
        "un-kriged_len_age_biomass_table.xlsx": "transect_length_age_biomass_report.xlsx"
    },
    "transect_results_full": {
        "EchoPro_un-kriged_output-08-Dec-2023_0.xlsx.xlsx": "transect_population_results_full.xlsx"
    },
    "transect_results_subset": {
        "EchoPro_un-kriged_output-08-Dec-2023_0.xlsx": "transect_population_results_nonzero.xlsx"
    }
}

####
echopro = "aged_len_haul_counts_table.xlsx"
echopop = "aged_length_haul_counts.xlsx"

# Read in file
echopro_aged_length_haul_counts = read_all_aged_length_haul_counts(ECHOPRO_ROOT / echopro)
echopop_aged_length_haul_counts = read_all_aged_length_haul_counts(ECHOPRO_ROOT / echopop)

plot_all_aged_length_haul_count_comparisons(
    echopro_dict=echopro_aged_length_haul_counts, 
    echopop_dict=echopop_aged_length_haul_counts
)



echopro = "total_len_haul_counts_table.xlsx"
echopop = "total_length_haul_counts.xlsx"
echopro_aged_length_haul_counts = read_all_aged_length_haul_counts(ECHOPRO_ROOT / echopro)
echopop_aged_length_haul_counts = read_all_aged_length_haul_counts(ECHOPRO_ROOT / echopop)
plot_all_aged_length_haul_count_comparisons(
    echopro_dict=echopro_aged_length_haul_counts, 
    echopop_dict=echopop_aged_length_haul_counts
)