# This YAML file is a configuration file specifying
# input filenames & some process parameter settings.
# Relative file paths defined below are concatenated
# with the data_root_dir path also set below.

---
##############################################################################
# Parameters

survey_year: 2019            # survey year being considered
species:
  text_code: pacific_hake    # target species for the survey year -- species name
  number_code: 22500         # target species for the survey year -- numeric code
##############################################################################
# Directory path that contains all input data needed

data_root_dir: C:/Users/Brandyn/Documents/GitHub/EchoPro_data/live_2019_files

##############################################################################
# Input data directories
input_directories: 
  acoustic:
    directory: acoustics/
    extension: zarr
  biological:
    directory: biology/
    extension: csv 
    file_name_formats:
      catch: "{DATE:YYYYMM}_{HAUL}_{FILE_ID:catch_perc}"
      length: "{DATE:YYYYMM}_{SPECIES_CODE}_{HAUL}_{FILE_ID:lf}"
      specimen: "{DATE:YYYYMM}_{SPECIES_CODE}_{HAUL}_{FILE_ID:spec}"
    file_index:
      catch: [haul_num]
      length: [haul_num, species_id]
      specimen: [haul_num, species_id]
    file_ids: 
      catch: catch_perc
      length: lf
      specimen: spec
...
