# This YAML file is a configuration file specifying
# input filenames & some process parameter settings.
# Relative file paths defined below are concatenated
# with the data_root_dir path also set below.

---
##############################################################################
# Parameters

survey_year: 2019            # survey year being considered

##############################################################################
# Directory path that contains all input data needed

data_root_dir: C:/Users/15052/Documents/GitHub/echopop_data/live_2019_files

##############################################################################
# Input data directories
input_directories: 
  acoustic:
    directory: acoustics/
    extension: zarr
  biological:
    directory: biology/
    extension: csv 
    file_ids: 
      catch: catch_perc
      length: lf
      specimen: spec
...
