# This YAML file is a configuration file specifying
# input filenames & some process parameter settings.
# Relative file paths defined below are concatenated
# with the data_root_dir path also set below.

---
##############################################################################
# Parameters

survey_year: 2019            # survey year being considered

##############################################################################
# Directory path that contains all input data needed

data_root_dir: C:/Users/Brandyn/Documents/GitHub/EchoPro_data/live_2019_files

##############################################################################
# Input data directories
input_directories: 
  acoustic:
    directory: acoustics/
    extension: zarr
    sheetname: null
  biological:
    directory: biology/
    extension: csv 
    sheetname: null 
...
