# This YAML file is a configuration file specifying
# input filenames & some process parameter settings.
# Relative file paths defined below are concatenated
# with the data_root_dir path also set below.

---
##############################################################################
# Parameters

survey_year: 2019            # survey year being considered
ship_id:
  160:
    survey: 201906
    name: NOAA Ship Bell M Shimada
    description: NOAA Fisheries Survey Vessel
  584:
    survey: 2019097
    name: FV Nordic Pearl
    description: Canadian Coast Guard
    haul_offset: 200
species:
  text_code: pacific_hake    # target species for the survey year -- species name
  number_code: 22500         # target species for the survey year -- numeric code
CAN_haul_offset: 200         # The value to be added to the Canadian's haul number

##############################################################################
# Report generation
###################
# Where the reports are saved
report_path: C:/Users/Brandyn/Documents/GitHub/EchoPro_data/Data/reports

##############################################################################
# Directory path that contains all input data needed

data_root_dir: C:/Users/Brandyn Lucca/Documents/Data/echopop_2019
# data_root_dir: C:/Users/Brandyn/Documents/GitHub/EchoPro_data/Data/

##############################################################################
# Input data files

biological:
  filename: Biological/1995-2023_biodata_redo.xlsx
  sheetname:
    catch: biodata_catch
    length: biodata_length
    specimen: biodata_specimen
stratification:
  strata:
    # The two stratification types are found in two sheets: "Base KS" and "INPFC"
    filename: Stratification/US_CAN strata 2019_final.xlsx
    sheetname: Base KS
  geo_strata:
    # The two stratification types are found in two sheets: "stratification1" and "INPFC"
    filename: Stratification/Stratification_geographic_Lat_2019_final.xlsx
    sheetname: [INPFC , stratification1]
NASC:
  # NASC values
  no_age1:
    # file that excludes age1 values
    # filename: Exports/US_CAN_NASC_2019_table_no_age1_test.xlsx
    filename: Exports/US_CAN_detailsa_2019_table2y+_ALL_final - updated.xlsx
    sheetname: Sheet1
  all_ages:
    # file that includes all ages
    # filename: Exports/US_CAN_NASC_2019_table_all_ages_test.xlsx
    filename: Exports/US_CAN_detailsa_2019_table1y+_ALL_final - updated.xlsx
    sheetname: Sheet1
kriging:
  mesh:
    filename: Kriging_files/Kriging_grid_files/krig_grid2_5nm_cut_centroids_2013.xlsx
    sheetname: krigedgrid2_5nm_forChu
  isobath_200m:
    filename: Kriging_files/Kriging_grid_files/transformation_isobath_coordinates.xlsx
    sheetname: Smoothing_EasyKrig
  vario_krig_para:
    # NOTE: This file is not currently used
    filename: Kriging_files/default_vario_krig_settings_2019_US_CAN.xlsx
    sheetname: Sheet1
...
