# This YAML file is a configuration file specifying
# input filenames & some process parameter settings.
# Relative file paths defined below are concatenated
# with the data_root_dir path also set below.

---
##############################################################################
# Parameters

survey_year: 2011            # survey year being considered
species:
  text_code: pacific_hake    # target species for the survey year -- species name
  number_code: 22500         # target species for the survey year -- numeric code
CAN_haul_offset: 100         # The value to be added to the Canadian's haul number

##############################################################################
# Report generation
###################
# Where the reports are saved
report_path: C:/Users/Brandyn/Documents/GitHub/echopop_2011/reports

##############################################################################
# Directory path that contains all input data needed
data_root_dir: C:/Users/Brandyn/Documents/GitHub/EchoPro_data/echopop_2011

##############################################################################
# Input data files

biological:
  length:
    US:
      filename: Biological/US/biodata_length.xlsx
      sheetname: Sheet1
    CAN:
      filename: Biological/CAN/biodata_length_Canada.xlsx
      sheetname: biodata_length_Canada
  specimen:
    US:
      filename: Biological/US/biodata_specimen.xlsx
      sheetname: Sheet1
    CAN:
      filename: Biological/CAN/biodata_specimen_Canada.xlsx
      sheetname: Sheet1
  catch:
    US:
      filename: Biological/US/biodata_catch.xlsx
      sheetname: Catch
    CAN:
      filename: Biological/CAN/biodata_catch_Canada.xlsx
      sheetname: Catch
stratification:
  strata:
    # The two stratification types are found in two sheets: "Base KS" and "INPFC"
    filename: Stratification/US&CAN strata 2011.xlsx
    sheetname: ["stratification #0 (INPFC)", "stratification by haul #1"]
  geo_strata:
    # The two stratification types are found in two sheets: "stratification1" and "INPFC"
    filename: Stratification/Stratification_geographic_Lat_rev.xlsx
    sheetname: ["stratification #0 (INPFC)", "stratification #1"]
NASC:
  # NASC values
  no_age1:
    # file that excludes age1 values
    filename: Exports/US_CAN_NASC_2011_table_no_age1.xlsx
    sheetname: Sheet1
  all_ages:
    # file that includes all ages
    filename: Exports/US_CAN_NASC_2011_table_all_ages.xlsx
    sheetname: Sheet1
export_regions:
  all_ages:
    filename: Stratification/US&CAN_2011_transect_region_haul_age1+ auto final_4-20-2019.xlsx
    sheetname: Sheet1
  no_age1:
    filename: Stratification/US&CAN_2011_transect_region_haul_age2+ auto final_4-20-2019.xlsx
    sheetname: Sheet1
kriging:
  mesh:
    filename: Kriging_files/Kriging_grid_files/krig_grid2_5nm_cut_centroids_2013.xlsx
    sheetname: krigedgrid2_5nm_forChu
  isobath_200m:
    filename: Kriging_files/Kriging_grid_files/transformation_isobath_coordinates.xlsx
    sheetname: Smoothing_EasyKrig
  vario_krig_para:
    # NOTE: This file is not currently used
    filename: Kriging_files/default_vario_krig_settings_final.xlsx
    sheetname: Sheet1
...
