# This YAML file is a configuration file specifying
# input filenames & some process parameter settings.
# Relative file paths defined below are concatenated
# with the data_root_dir path also set below.

---
##############################################################################
# Parameters

survey_year: 2015            # survey year being considered
species:
  text_code: pacific_hake    # target species for the survey year -- species name
  number_code: 22500         # target species for the survey year -- numeric code
CAN_haul_offset: 200         # The value to be added to the Canadian's haul number

##############################################################################
# Report generation
###################
# Where the reports are saved
report_path: C:/Users/Brandyn/Documents/GitHub/echopop_2015/reports

##############################################################################
# Directory path that contains all input data needed
data_root_dir: C:/Users/Brandyn/Documents/GitHub/EchoPro_data/echopop_2015

##############################################################################
# Input data files

biological:
  length:
    US:
      filename: Biological/US/2015_biodata_length.xlsx
      sheetname: 2015_Biodata_length
    CAN:
      filename: Biological/CAN/2015_biodata_length_CAN.xlsx
      sheetname: biodata_length_CAN
  specimen:
    US:
      filename: Biological/US/2015_biodata_specimen.xlsx
      sheetname: 2015_biodata_specimen
    CAN:
      filename: Biological/CAN/2015_biodata_specimen_CAN.xlsx
      sheetname: biodata_specimen_CAN
  catch:
    US:
      filename: Biological/US/2015_biodata_catch.xlsx
      sheetname: 2015_Biodata_Catch
    CAN:
      filename: Biological/CAN/2015_biodata_catch_CAN.xlsx
      sheetname: biodata_catch_CAN
stratification:
  strata:
    # The two stratification types are found in two sheets: "Base KS" and "INPFC"
    filename: Stratification/US&CAN strata 2015 shoreside.xlsx
    sheetname: Base KS
  geo_strata:
    # The two stratification types are found in two sheets: "stratification1" and "INPFC"
    filename: Stratification/Stratification_geographic_Lat_2015_shoreside.xlsx
    sheetname: [INPFC , stratification1]
NASC:
  # NASC values
  no_age1:
    # file that excludes age1 values
    filename: Exports/US_CAN_NASC_2015_table_no_age1_test.xlsx
    sheetname: Sheet1
  all_ages:
    # file that includes all ages
    filename: Exports/US_CAN_NASC_2015_table_all_ages_test.xlsx
    sheetname: Sheet1
kriging:
  mesh:
    filename: Kriging_files/Kriging_grid_files/krig_grid2_5nm_cut_centroids_2013.xlsx
    sheetname: krigedgrid2_5nm_forChu
  isobath_200m:
    filename: Kriging_files/Kriging_grid_files/transformation_isobath_coordinates.xlsx
    sheetname: Smoothing_EasyKrig
  vario_krig_para:
    # NOTE: This file is not currently used
    filename: Kriging_files/default_vario_krig_settings_2015_US_CAN.xlsx
    sheetname: Sheet1
...
