% test mesage

clear

msg1='EasyKrig Explanation';
msg2={'Explanation, K>> varargin{1} ans =' ...
' EasyKrig3.0 ' ...
' p=general_mes); ' ...
' ??? Error using ==> str2func' ...
' Invalid function name ''EasyKrig3.0''.' ...
' Error in ==> C:\Projects\EasyKrig\EasyKrig_V3.0-V6x\help\general_message.m' ...
' On line 36  ==>     gui_State.gui_Callback = str2func(varargin{1}); >> p=general_message(''help_message'',''EasyKrig3.0'',''Explanation'');' ...
'    ' ...
'    ' ...
'>> p=general_message(''help_message'',''EasyKrig3.0'',''Explanation'');' ...
' K>> varargin{2} ans =' ...
' EasyKrig3.0 ' ...
'  ...'  ...
' On line 36  ==>     gui_State.gui_Callback = str2func(varargin{1});' ...
'    ' ...
'    ' ...
'>> p=general_message(''help_message'',''EasyKrig3.0'',''Explanation'');' ...
' K>> varargin{2} ans =' ...
' EasyKrig3.0 ' ...
' p=general_mes); ' ...
' ??? Error using ==> str2func' ...
' Invalid function name ''EasyKrig3.0''.' ...
' Error in ==> C:\Projects\EasyKrig\EasyKrig_V3.0-V6x\help\general_message.m' ...
' On line 36  ==>     gui_State.gui_Callback = str2func(varargin{1}); >> p=general_message(''help_message'',''EasyKrig3.0'',''Explanation'');' ...
'    ' ...
'    ' ...
'>> p=general_message(''help_message'',''EasyKrig3.0'',''Explanation'');' ...
' K>> varargin{2} ans =' ...
' EasyKrig3.0 ' ...
'  ...'  ...
' On line 36  ==>     gui_State.gui_Callback = str2func(varargin{1});' ...
'    ' ...
'    ' ...
'>> p=general_message(''help_message'',''EasyKrig3.0'',''Explanation'');' ...
' K>> varargin{2} ans =' ...
' EasyKrig3.0 ' ...
'  ...'};
hmsg=general_message('no_action',msg1,msg2);