# Publish archives to PyPI and TestPyPI using GitHub Actions
name: Publish to PyPI

# Permissions
permissions:
  contents: read
  id-token: write

# Only run for tagged releases
on:
  release:
    types:
      - released
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-artifact:
    name: Build echopop package
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        # fetch all history so that setuptools-scm works
        fetch-depth: 0
        fetch-tags: true

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: python -m pip install --upgrade pip build setuptools>=64.0.0 setuptools_scm[toml]>=8.0 wheel

    - name: Build distributions
      run: |
        python -m build --sdist --wheel --no-isolation
        ls -lh dist/

    - uses: actions/upload-artifact@v7
      with:
        name: releases
        path: dist

  publish-test-pypi:
    name: Publish and Verify on TestPyPI
    needs: build-artifact
    runs-on: ubuntu-22.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: releases
          path: dist

      - name: Upload to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.14.0
        with:
          repository-url: https://test.pypi.org/legacy/
          # Ensure you have a secret named TEST_PYPI_API_TOKEN
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          skip-existing: true

      - name: Wait for indexing
        run: sleep 60  # TestPyPI takes a minute to update its index

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Verify installation from TestPyPI
        run: |
          python -m pip install --upgrade pip
          # Force pip to check TestPyPI for echopop, but PyPI for other dependencies
          VERSION=${{ github.ref_name }}
          python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ echopop==${VERSION#v}
          python -c "import echopop; print('TestPyPI Install Success! Version:', echopop.__version__)"

  publish-pypi:
    runs-on: ubuntu-22.04
    needs: publish-test-pypi
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: releases
          path: dist

      - name: Publish to PyPI (Trusted)
        uses: pypa/gh-action-pypi-publish@v1.14.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
          skip-existing: true
